### ISSUE TITLE
should need return old kernel32 For XP support?

### ISSUE THREAD

**Issue by svcino** [jacob1/The-Powder-Toy#29] opened 2019-09-03 09:34 UTC
need return XP support

**Comment by jacob1** [comment] 2019-09-03 13:43
We already support xp. What makes you think we don't?

If there's a bug where we actually don't support xp, I'd like to know. I probably won't fix it, but at least I know I can uncheck "xp support" in visual studio.

**Comment by jacob1** [comment] 2019-10-04 13:49
You still don't make any sense.

We **still** support Windows XP. TPT is already 32 bit. If you are getting a problem launching TPT, please paste the exact error message, then maybe I can figure out what the problem is.

**Comment by svcino** [comment] 2019-10-05 03:36
> You still don't make any sense.
> 
> We **still** support Windows XP. TPT is already 32 bit. If you are getting a problem launching TPT, please paste the exact error message, then maybe I can figure out what the problem is.

initializeCriticalSectionEX error

**Comment by jacob1** [comment] 2019-10-05 03:45
ok, that should be enough info for me to research this a little.

Also I'd like to have something confirmed, does the official version also do this? Or only my mod. You opened this issue in my mod's repository, so maybe it only affects my mod?
Official version: https://powdertoy.co.uk/Discussions/Categories/Index.html

**Comment by jacob1** [comment] 2021-11-12 20:37
Closing as I have no plans to add XP support

**Closed as completed by jacob1** 2021-11-12 20:37 UTC
