### ISSUE TITLE
Previews not displaying after deleting saved simulation

### ISSUE THREAD

**Issue by filcuk** [jacob1/The-Powder-Toy#11] opened 2017-05-12 13:21 UTC
Am I allowed to add things here❓ 

To replicate:
1. Create simulation
2. Save simulation
3. Delete simulation from saves list **using top-right corner button** (the 'no entry' road sign)

Previews will not show anywhere until you exit the save list into a new simulation.

Version: 35.2 (build 78)

**Comment by filcuk** [comment] 2017-05-12 13:39
I found this happens in different scenarios too, but I don't know how to replicate those yet.

**Comment by jacob1** [comment] 2017-05-12 20:40
Yes opening issues here is fine, you'll get a response much faster than the in game bug reporter. I can look at it when I am home later.

I've tried fixing at least twice bugs where the previews aren't there. It used to be far worse. Eventually I'm just going to rewrite the save browser, but it would be nice to fix this properly first since the rewrite is long off.

This should be easier to fix though if it is highly reproduceable. Maybe fixing this will fix the bug entirely!

**Comment by jacob1** [comment] 2017-05-15 01:14
fixed in 3ad6b1e200be9718f0de4d2590d4b41fa758a336

The bug happens when you download some save previews, then wait 5-15 seconds and try to download some more (deleting a save triggers a thumbnail redownload for some reason). Probably the main reason you noticed with that, is because you often do that after 5-15 seconds.

15 seconds is an internal HTTP timeout, 5 seconds seems to be some kind of server side thing? Not sure

**Closed as completed by jacob1** 2017-05-15 01:14 UTC
